### ISSUE TITLE
Voucher Entry - Mark USE TAXABLE invoices

### ISSUE THREAD

**Issue by YoMurphy** [scaspers/ServiceMaster#3]
Add "UT" or "TAX" command in voucher entry that will mark an invoice as USE TAXABLE with a popup field to enter the amount Taxable. This would compile a list of Use Tax invoices and a running total for each Fiscal Period.

**Comment by scaspers** [comment]
Voucher entry screens and the adjustment screen now have "UT" command to enter\edit the amount that is subject to USE TAX.  A new report is also available and will be added to the month end close checklist.
