### ISSUE TITLE
Customer Interest or Personal Comments field

### ISSUE THREAD

**Issue by YoMurphy** [scaspers/ServiceMaster#6]
Have a field in work orders to place individual/personal comments. Comments such as pets name, favorite band, recent vacations, ect. Items to help create a better bond with our customer, personalize the interaction and cement our relationship.

**Comment by YoMurphy** [comment]
Inspired by this article:
https://www.ratchetandwrench.com/articles/print/4763-selling-maintenance-to-millennials

**Comment by scaspers** [comment]
Would "SN" service notes work for this?  These notes follow the customer.

**Comment by scaspers** [comment]
The SN option from the work order menu has been modified to use the GUI textbox editor.  This data field has also been added to the API data for use with tablets.  

Will we need any other display options for the terminal users?
